<a href="https://www.kaggle.com/code/secretiveplotter1863/eda-aapl-next-day-close-prediction-model?scriptVersionId=336955491" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub

/kaggle/input/datasets/tarunpaparaju/apple-aapl-historical-stock-data/HistoricalQuotes.csv

Develop and evaluate a single-ticker next-day close prediction model for AAPL using only past price/volume data, with time-based validation and visual analysis of prediction errors.

In [2]:
stock=pd.read_csv('/kaggle/input/datasets/tarunpaparaju/apple-aapl-historical-stock-data/HistoricalQuotes.csv')
stock

            Date  Close/Last     Volume       Open       High        Low
0     02/28/2020     $273.36  106721200    $257.26    $278.41    $256.37
1     02/27/2020     $273.52   80151380     $281.1       $286    $272.96
2     02/26/2020     $292.65   49678430    $286.53    $297.88     $286.5
3     02/25/2020     $288.08   57668360    $300.95    $302.53    $286.13
4     02/24/2020     $298.18   55548830    $297.26    $304.18    $289.23
...          ...         ...        ...        ...        ...        ...
2513  03/05/2010    $31.2786  224647427   $30.7057   $31.3857   $30.6614
2514  03/04/2010    $30.1014   89591907   $29.8971   $30.1314   $29.8043
2515  03/03/2010    $29.9043   92846488   $29.8486   $29.9814   $29.7057
2516  03/02/2010    $29.8357  141486282     $29.99   $30.1186   $29.6771
2517  03/01/2010    $29.8557  137312041   $29.3928   $29.9286     $29.35

[2518 rows x 6 columns]

In [3]:
print(stock.dtypes)

Date           object
 Close/Last    object
 Volume         int64
 Open          object
 High          object
 Low           object
dtype: object

In [4]:
stock['Date']=pd.to_datetime(stock["Date"], format="%m/%d/%Y")
df_sorted =stock.sort_values(by="Date", ascending=True)
df_sorted

           Date  Close/Last     Volume       Open       High        Low
2517 2010-03-01    $29.8557  137312041   $29.3928   $29.9286     $29.35
2516 2010-03-02    $29.8357  141486282     $29.99   $30.1186   $29.6771
2515 2010-03-03    $29.9043   92846488   $29.8486   $29.9814   $29.7057
2514 2010-03-04    $30.1014   89591907   $29.8971   $30.1314   $29.8043
2513 2010-03-05    $31.2786  224647427   $30.7057   $31.3857   $30.6614
...         ...         ...        ...        ...        ...        ...
4    2020-02-24     $298.18   55548830    $297.26    $304.18    $289.23
3    2020-02-25     $288.08   57668360    $300.95    $302.53    $286.13
2    2020-02-26     $292.65   49678430    $286.53    $297.88     $286.5
1    2020-02-27     $273.52   80151380     $281.1       $286    $272.96
0    2020-02-28     $273.36  106721200    $257.26    $278.41    $256.37

[2518 rows x 6 columns]

In [5]:
stock.columns = stock.columns.str.strip()

In [6]:
stock['High'].dtypes

dtype('O')